config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
 get "/about" => "home#about", as: :about

 resources :projects do
   resources :discussions
end
resources :discussions, only: [] do
  resources :comments
end

root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base 
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase
  include Ckeditor::Backend::Paperclip
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/attachments/:id/:filename',
                    path: ':rails_root/public/ckeditor_assets/attachments/:id/:filename'

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 100.megabytes
  do_not_validate_attachment_file_type :data

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  has_attached_file :data,
                    url: '/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    path: ':rails_root/public/ckeditor_assets/pictures/:id/:style_:basename.:extension',
                    styles: { content: '800>', thumb: '118x100#' }

  validates_attachment_presence :data
  validates_attachment_size :data, less_than: 2.megabytes
  validates_attachment_content_type :data, content_type: /\Aimage/

  def url_content
    url(:content)
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :discussion
end

app/models/discussion.rb
class Discussion < ApplicationRecord
  belongs_to :project
  has_many :comments, dependent: :destroy
end

app/models/project.rb
class Project < ApplicationRecord

  has_many :discussions, dependent: :destroy
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @comment = Comment.new
  end

  def create
    discussion_id = params[:discussion_id]
    discussion = Discussion.find discussion_id
    # @comment = @discussion.comments.new find_params
    if discussion.comments.create find_params
      redirect_to project_path(discussion.project_id)
    else
      flash[:alert] = "wrong information"
      redirect_to project_path(discussion.project_id)
    end
  end

  def destroy

  end


  private

  def find_params
 params.require(:comment).permit(:body)
  end
end

app/controllers/discussions_controller.rb
class DiscussionsController < ApplicationController
  def create
    @discussion = Discussion.new params.require(:discussion).permit(:title, :description)
    @project = Project.find params[:project_id]
    @discussion.project = @project

    if @discussion.save
      redirect_to project_path(@project)
    else
      flash[:alert] = "Somethings is wrong"
        render "/projects/show"
   end
end
  def destroy
    p = Project.find params[:project_id]
    d = Discussion.find params[:id]
    d.destroy
    redirect_to project_path(p), notice: "answer deleted"

  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index

  end

  def about

  end
  
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
    before_action :find_project, only: [:show, :edit, :update, :destroy]

    def index
        @project = Project.all
    end

    def show
        @project = Project.find params[:id]
        @discussion = Discussion.new
        @discussions = @project.discussions

        # @dis = Discussion.find params[]
        @comment = Comment.new
    end

    def edit
        @project = Project.find params[:id]
    end

    def update
        @project = Project.find params[:id]
        if @project.update project_params

            redirect_to project_path
        else
            flash[:alert] = 'wront information'
            render :edit
        end
    end

    def new
        @project = Project.new
    end

    def create
        @project = Project.new project_params
        if @project.save
            redirect_to projects_path, notice: ' successfull'

        else
            flash[:alert] = ' wrong information'
            render :new
        end
    end

    def destroy
      @project = Project.find params[:id]
      @project.destroy
        redirect_to projects_path, notice: " Project successfully deleted"
    end

    private
    def find_project
      @project = Project.find params[:id]
    end
    def project_params
        params.require(:project).permit(:title, :description, :bootsy_image_gallery_id)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/discussions_helper.rb
module DiscussionsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/comments/_form.html.erb
<!-- Button trigger modal -->
<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#myModal">
    Add comment

</button>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                <h4 class="modal-title" id="myModalLabel">Post Comments</h4>
            </div>
            <div class="modal-body">

                <%= form_for [disc, @comment] do |f| %>

                <%= f.label :body %>
                <%= f.text_area :body  %>
                <%= f.submit "Submit", class: "btn btn-default" %>


                  </div>
                    <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>


                  </div>
                <% end %>
        </div>
    </div>
</div>

app/views/comments/_showcomments.html.erb
  <% count = 1 %>
<% disc.comments.each do |f| %>
<div class="container comment-box">


<span style="font-size: 10  px  "> <%= count %>.</span> <%= f.body %>
<% count +=1 %>
</div>
<% end %>

app/views/home/about.html.erb
this is my about page

app/views/home/index.html.erb
this is my home page

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PmTool2</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
    <%= link_to "Home", root_path %>
    |
    <%= link_to "About", about_path %>
    |
    <%= link_to "Projects", projects_path %>
    |
    <%= link_to "New Project", new_project_path %>

  </div>
<hr>
<% if flash[:notice] %>
<div class="alert alert-success" role="alert">
 <%= flash[:notice] %>
</div>
<% end %>
<% if flash[:alert] %>
<div class="alert alert-danger" role="alert">
 <%= flash[:alert] %>
</div>

<% end %>
  <br>
  <div class="container">
    <%= yield %>
  </div>
  </body>
</html>

app/views/projects/edit.html.erb
  <%= form_for @project, class:"form-horizontal" do |f| %>
   <div class="form-group">
  <%= f.label :title %>
  <%= f.text_field :title, class: 'form-control' %>
  </div>
   <div class="form-group">
  <%= f.label :description %>
  <%= f.cktext_area :description, as: :bootsy, class: 'form-control' %>
  </div>
  <div>
    <%= f.submit "Update", class:"btn btn-default", role: "button" %>
  </div>
  <% end %>

app/views/projects/index.html.erb
Project list

<table class="table table-striped">
<thead>
  <tr>
<th>title</th>
<th>description</th>
<th> actin</th>
  </tr>
</thead>

<tbody>
  <% @project.each do |f| %>
<tr>
<td><%= f.title  %></td>
<td><%= raw f.description.first(250) %></td>
<td><%= link_to "Edit", project_path(f.id) %></td>
</tr>
<% end %>
</tbody>
</table>

app/views/projects/new.html.erb
<%= form_for @project, class:"form-horizontal" do |f| %>
 <div class="form-group">
<%= f.label :title %>
<%= f.text_field :title, class: 'form-control' %>
</div>
 <div class="form-group">
<%= f.label :description %>
<%= f.cktext_area :description, as: :bootsy, class: 'form-control' %>
</div>
<div>
  <%= f.submit "create Project", class:"btn btn-default", role: "button" %>
</div>
<% end %>

app/views/projects/show.html.erb
<center>
    <h1><%= @project.title %></h1>
</center>
<p><%= raw @project.description %></p>
<%= link_to "Edit", edit_project_path(@project) %>
<%= link_to "Delete", project_path(@project.id), method: :delete %>
<hr>

<% if @project.discussions.any? %>
<center><h4>Disscussion</h4></center>
<% c= 0 %>
  <% @project.discussions.each do |disc| %>
    <div><% c +=1 %>
      <h2><%= disc.title %> </h2><span style="font-size:10px "> Discussion #<%= c %></span>
      <span><%= link_to "Delete", project_discussion_path(@project, disc), class: "btn btn-info btn-sm", method: :delete, data: {confirm: "Are you sure?"} %></span>
    </div>
    <br>
    <div style="float:right, float:clear">
      <p><%= raw disc.description %></p>
    </div>
    <div>

      <%= render partial: "comments/form", locals: {disc: disc} %>
    </div>

    <div>
      <%= render partial: "comments/showcomments", locals: {disc: disc} %>

    </div>
  <% end %>
<% end %>




                    <%= form_for [@project, @discussion],class: "form-group" do |f| %>
                    <div>
                        <%= f.label :title %>
                        <%= f.text_field :title, class: "form-control" %>
                    </div>
                    <div>
                        <%= f.label :description %>
                        <%= f.cktext_area :description, class: "form-control",row: "3" %>
                    </div>

                    <%= f.submit "Submit a Discussion", class: "btn btn-default" %>


    <%end %>